### ISSUE TITLE
Deploy on Docker/Heroku

### ISSUE THREAD

**Issue by LorenRd** [Proyecto-FIS/api-gateway#1]
Echadle un ojo si podéis al despliegue con Docker en Heroku, en local está funcionando.

Haced npm install, npm start y te empieza a mapear las peticiones de localhost:3000/products (U otro endpoint) a la url de los microservicios desplegados en Heroku.

![image](https://user-images.githubusercontent.com/11414362/101837442-5b8edd80-3b3f-11eb-8f0a-d74bb57fdf61.png)

Con docker parece que no le llegan las peticiones a pesar de que he puesto el puerto 3000 en el Dockerfile...
Está automatizado el despliegue por lo que si pusheais a master se debe desplegar en Heroku ya

**Comment by amgdev9** [comment]
Ya funca esto en Heroku, el campo host de apiEndpoints debe ser "*", de lo contrario no va a aceptar conexiones del exterior
